name: Scorecard - Chainlit

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  scorecard:
    uses: ./.github/workflows/scorecard-template.yml
    with:
      repo: 'Chainlit/chainlit'
    secrets:
      SCORECARD_GITHUB_TOKEN: ${{ secrets.SCORECARD_GITHUB_TOKEN }}
